# Workforce Analysis

In [ ]:
import pandas as pd 
import numpy as np

Pandas (pd), NumPy (np) and sqlalchemy live.

In [ ]:
#Load and preview data
df_raw = pd.read_csv('employee_dataset_raw.csv')
df_raw.info()
df_raw.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   EmployeeID             10000 non-null  str
 1   Age                    10000 non-null  int64
 2   Department             10000 non-null  str
 3   JobLevel               10000 non-null  int64
 4   YearsAtCompany         10000 non-null  int64
 5   MonthlyIncome          10000 non-null  int64
 6   JobSatisfaction        10000 non-null  int64
 7   WorkLifeBalance        10000 non-null  int64
 8   OverTime               10000 non-null  str
 9   DistanceFromHome       10000 non-null  float64
 10  PromotionLast5Years    10000 non-null  str
 11  PerformanceRating      10000 non-null  int64
 12  TrainingHoursLastYear  10000 non-null  int64
 13  Attrition              10000 non-null  str
dtypes: float64(1), int64(8), str(5)
memory usage: 1.1 MB

,EmployeeID,Age,Department,JobLevel,YearsAtCompany,MonthlyIncome,JobSatisfaction,WorkLifeBalance,OverTime,DistanceFromHome,PromotionLast5Years,PerformanceRating,TrainingHoursLastYear,Attrition
0,EMP0000,42,Sales,3,9,9866,4,1,No,24.5,Yes,4,19,No
1,EMP0001,36,Sales,3,7,8958,3,3,No,10.0,No,2,13,No
2,EMP0002,44,Sales,4,16,11716,4,3,No,4.0,No,4,13,No
3,EMP0003,53,Finance,4,30,17061,5,3,No,7.1,No,3,20,No
4,EMP0004,35,HR,2,4,5738,2,3,No,8.4,No,2,15,No

In [ ]:
#Create a copy of dataset to protect raw
df_cleaned = df_raw.copy()

#Fix irregular column header formatting
df_cleaned.columns = (df_cleaned.columns
      .str.replace(r'([a-z0-9])([A-Z])', r'\1_\2', regex=True)
      .str.replace(r'([a-zA-Z])([0-9])', r'\1_\2', regex=True)
      .str.replace(r'([0-9])([a-zA-Z])', r'\1_\2', regex=True)
      .str.lower())

df_cleaned.head(10)

,employee_id,age,department,job_level,years_at_company,monthly_income,job_satisfaction,work_life_balance,over_time,distance_from_home,promotion_last_5_years,performance_rating,training_hours_last_year,attrition
0,EMP0000,42,Sales,3,9,9866,4,1,No,24.5,Yes,4,19,No
1,EMP0001,36,Sales,3,7,8958,3,3,No,10.0,No,2,13,No
2,EMP0002,44,Sales,4,16,11716,4,3,No,4.0,No,4,13,No
3,EMP0003,53,Finance,4,30,17061,5,3,No,7.1,No,3,20,No
4,EMP0004,35,HR,2,4,5738,2,3,No,8.4,No,2,15,No
5,EMP0005,35,Sales,1,1,3839,2,3,No,3.1,No,2,18,No
6,EMP0006,53,IT,4,31,17377,3,3,No,8.9,No,4,18,No
7,EMP0007,45,Finance,2,5,8463,4,3,No,17.6,No,2,8,No
8,EMP0008,33,HR,2,8,6956,5,3,No,3.6,No,2,7,No
9,EMP0009,43,Engineering,2,4,9383,1,3,Yes,8.6,No,3,10,No

In [ ]:
#Standardise data within string columns
text_cols = df_cleaned.select_dtypes(include=['object', 'string']).columns

for col in text_cols:
    df_cleaned[col] = (
        df_cleaned[col]
        .fillna('unknown')
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
        .str.lower())

for col in text_cols:
    df_cleaned[col] = df_cleaned[col].fillna('unknown')

initial_rows = len(df_cleaned)
df_cleaned = df_cleaned.drop_duplicates()
final_rows = len(df_cleaned)
if initial_rows != final_rows:
    print(f"⚠️ Removed {initial_rows - final_rows} absolute duplicate rows.")

duplicates = df_cleaned['employee_id'].duplicated().sum()
print(f"Duplicate employee IDs: {duplicates}")

df_cleaned.head(5)

Duplicate employee IDs: 0

,employee_id,age,department,job_level,years_at_company,monthly_income,job_satisfaction,work_life_balance,over_time,distance_from_home,promotion_last_5_years,performance_rating,training_hours_last_year,attrition
0,emp0000,42,sales,3,9,9866,4,1,no,24.5,yes,4,19,no
1,emp0001,36,sales,3,7,8958,3,3,no,10.0,no,2,13,no
2,emp0002,44,sales,4,16,11716,4,3,no,4.0,no,4,13,no
3,emp0003,53,finance,4,30,17061,5,3,no,7.1,no,3,20,no
4,emp0004,35,hr,2,4,5738,2,3,no,8.4,no,2,15,no

In [ ]:
#Values check
print("1. Number of NA values per column")
print(df_cleaned.isna().sum())
print('')

print("2. Number of Duplicate employee_ID (should be 0)")
df_cleaned['employee_id'].duplicated().sum()

1. Number of NA values per column
employee_id                 0
age                         0
department                  0
job_level                   0
years_at_company            0
monthly_income              0
job_satisfaction            0
work_life_balance           0
over_time                   0
distance_from_home          0
promotion_last_5_years      0
performance_rating          0
training_hours_last_year    0
attrition                   0
dtype: int64

2. Number of Duplicate employee_ID (should be 0)

np.int64(0)

In [ ]:
#AI copy and paste cell to help with the next section
print(df_cleaned.head(10).to_string())
print(df_cleaned.info())

  employee_id  age   department  job_level  years_at_company  monthly_income  job_satisfaction  work_life_balance over_time  distance_from_home promotion_last_5_years  performance_rating  training_hours_last_year attrition
0     emp0000   42        sales          3                 9            9866                 4                  1        no                24.5                    yes                   4                        19        no
1     emp0001   36        sales          3                 7            8958                 3                  3        no                10.0                     no                   2                        13        no
2     emp0002   44        sales          4                16           11716                 4                  3        no                 4.0                     no                   4                        13        no
3     emp0003   53      finance          4                30           17061                 5                  3        no                 7.1                     no                   3                        20        no
4     emp0004   35           hr          2                 4            5738                 2                  3        no                 8.4                     no                   2                        15        no
5     emp0005   35        sales          1                 1            3839                 2                  3        no                 3.1                     no                   2                        18        no
6     emp0006   53           it          4                31           17377                 3                  3        no                 8.9                     no                   4                        18        no
7     emp0007   45      finance          2                 5            8463                 4                  3        no                17.6                     no                   2                         8        no
8     emp0008   33           hr          2                 8            6956                 5                  3        no                 3.6                     no                   2                         7        no
9     emp0009   43  engineering          2                 4            9383                 1                  3       yes                 8.6                     no                   3                        10        no
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               10000 non-null  str
 1   age                       10000 non-null  int64
 2   department                10000 non-null  str
 3   job_level                 10000 non-null  int64
 4   years_at_company          10000 non-null  int64
 5   monthly_income            10000 non-null  int64
 6   job_satisfaction          10000 non-null  int64
 7   work_life_balance         10000 non-null  int64
 8   over_time                 10000 non-null  str
 9   distance_from_home        10000 non-null  float64
 10  promotion_last_5_years    10000 non-null  str
 11  performance_rating        10000 non-null  int64
 12  training_hours_last_year  10000 non-null  int64
 13  attrition                 10000 non-null  str
dtypes: float64(1), int64(8), str(5)
memory usage: 1.1 MB
None

In [ ]:
#Export the cleaned dataset
df_cleaned.to_csv('employee_dataset_cleaned.csv', index=False)
print("Data successfully exported to CSV ready for SQL")

Data successfully exported to CSV ready for SQL